apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
  name: nginx-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 82
    targetPort: 80
  externalIPs: ["192.168.50.4"]
  selector:
    app: nginx
